language: python
python:
    - 2.7

virtualenv:
    system_site_packages: true

env:
    global:
        - secure: "CPt377sadrE3Wp70beQs8rnlzHkldtN1EOFfr+1CEkuHQJng4bdMmdaEohfe0+6hXMkXWOc6fYdjdrv9JuY06NWmWcTfKryV4CB9GCrbAPibsxiLDzgcXjQjd2jCn3DAAMXOG5ANqmr98IWOHiK7Z6DrNhFTGzoVBIoiXeRKOrA="

before_install:
    - gem install compass
    - gem install sass
    - gem install sass-rails
    - gem install bootstrap-sass --version 2.3.2.2
    - npm install -g grunt-cli
    - npm install

install:
    - pip install -r requirements.txt

before_script:
    - source travis_before.sh

script:
    - source travis_spec.sh
    - cd www

branches:
  only:
    - master
    - develop

notifications:
  email:
    - maxime@naeka.fr
    - thomas@naeka.fr
    - leo@naeka.fr
  hipchat:
    rooms:
      - secure: "FUTli6PhsUHy/k1g30Yz98ngGwDE152MUXp9I7RwamVFcmeehHO0TVyeTw+r/2JCScsJMg4F2swUAHbvGSufCdUy6o7cNlepnjQzPOgKTba3WxZsLoX40oUdRAl3904yq3MB/b+ZPfAv54qP3EqPVJoO7jDLGv6UTibpFOEwaLo="
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} (<a href="%{build_url}">Details</a>)'
    format: html