language: python
python:
    - 2.7

virtualenv:
    system_site_packages: true

env:
    global:
        - secure: "CPt377sadrE3Wp70beQs8rnlzHkldtN1EOFfr+1CEkuHQJng4bdMmdaEohfe0+6hXMkXWOc6fYdjdrv9JuY06NWmWcTfKryV4CB9GCrbAPibsxiLDzgcXjQjd2jCn3DAAMXOG5ANqmr98IWOHiK7Z6DrNhFTGzoVBIoiXeRKOrA="

before_install:
    - gem install compass
    - gem install sass
    - gem install sass-rails
    - gem install bootstrap-sass
    - npm install -g grunt-cli
    - npm install

install:
    - pip install -r requirements.txt

before_script:
    - source travis_before.sh

script:
    - source travis_spec.sh
    - cd www

branches:
  only:
    - master
    - develop

notifications:
  email:
    - maxime@naeka.fr
    - thomas@naeka.fr
    - leo@naeka.fr
